apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../ai-eng

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  - AUTH_EMAIL_DOMAIN=cluster.local
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: 43399d5fd4fe9fc288329739aa454765353fae13
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: 438160e48e6cc5c7dc85b6cfa7c6a2cdf33b42c3
