apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../ai-eng

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  - AUTH_EMAIL_DOMAIN=cluster.local
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: cfc28e88d76070dd08829764787060a901373513
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: d6e5659cd296af8713b2c960edba80aa57372196
