apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../../base

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: fa5c3962a3ad5afde67ef2fac867c85405f47aea
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: fa5c3962a3ad5afde67ef2fac867c85405f47aea
