apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
  - ../../base

patches:
  - path: route-patch.yaml
  - path: api-route-patch.yaml

images:
  - name: quay.io/org-pulse/team-tracker-backend
    newTag: "2c4c6db3d5eedc1ffdd41ae16d92ad1859a0fe79"
  - name: quay.io/org-pulse/team-tracker-frontend
    newTag: "2c4c6db3d5eedc1ffdd41ae16d92ad1859a0fe79"
