/**
 * Static quality report registry — auto-generated by generate-quality-registry.sh
 * Each reportUrl is resolved by Vite (?url) so the browser loads a full HTML document
 * inside an iframe — no v-html.
 */
import reportKserveKserve from './generated-reports/quality-report-kserve-kserve.html?url'
import reportRedHatDataServicesKserve from './generated-reports/quality-report-red-hat-data-services-kserve.html?url'
import reportOpendatahubIoKserve from './generated-reports/quality-report-opendatahub-io-kserve.html?url'
import reportOpendatahubIoOpenvinoGenai from './generated-reports/quality-report-opendatahub-io-openvino.genai.html?url'
import reportOpendatahubIoOpenvino from './generated-reports/quality-report-opendatahub-io-openvino.html?url'
import reportOpenvinotoolkitOpenvino from './generated-reports/quality-report-openvinotoolkit-openvino.html?url'
import reportRedHatDataServicesModelsAsAService from './generated-reports/quality-report-red-hat-data-services-models-as-a-service.html?url'
import reportOpenvinotoolkitOpenvinoGenai from './generated-reports/quality-report-openvinotoolkit-openvino.genai.html?url'
import reportOpendatahubIoModelsAsAService from './generated-reports/quality-report-opendatahub-io-models-as-a-service.html?url'
import reportOpendatahubIoOpenvinoTokenizers from './generated-reports/quality-report-opendatahub-io-openvino_tokenizers.html?url'
import reportOpenvinotoolkitOpenvinoTokenizers from './generated-reports/quality-report-openvinotoolkit-openvino_tokenizers.html?url'
import reportRedHatDataServicesOpenvinoModelServer from './generated-reports/quality-report-red-hat-data-services-openvino_model_server.html?url'
import reportRedHatDataServicesOpenvino from './generated-reports/quality-report-red-hat-data-services-openvino.html?url'
import reportOpendatahubIoMlserver from './generated-reports/quality-report-opendatahub-io-MLServer.html?url'
import reportOpenvinotoolkitModelServer from './generated-reports/quality-report-openvinotoolkit-model_server.html?url'
import reportRedHatDataServicesModelmeshServing from './generated-reports/quality-report-red-hat-data-services-modelmesh-serving.html?url'
import reportOpendatahubIoModelmeshServing from './generated-reports/quality-report-opendatahub-io-modelmesh-serving.html?url'
import reportOpendatahubIoOdhModelController from './generated-reports/quality-report-opendatahub-io-odh-model-controller.html?url'
import reportOpendatahubIoVllmTgisAdapter from './generated-reports/quality-report-opendatahub-io-vllm-tgis-adapter.html?url'
import reportRedHatDataServicesOdhModelController from './generated-reports/quality-report-red-hat-data-services-odh-model-controller.html?url'
import reportRedHatDataServicesMlserver from './generated-reports/quality-report-red-hat-data-services-MLServer.html?url'
import reportOpendatahubIoOpenvinoModelServer from './generated-reports/quality-report-opendatahub-io-openvino_model_server.html?url'
import reportSeldonioMlserver from './generated-reports/quality-report-SeldonIO-MLServer.html?url'
import reportKserveModelmeshServing from './generated-reports/quality-report-kserve-modelmesh-serving.html?url'
import reportOpendatahubIoCaikitNlpClient from './generated-reports/quality-report-opendatahub-io-caikit-nlp-client.html?url'
import reportRedHatDataServicesModelmeshRuntimeAdapter from './generated-reports/quality-report-red-hat-data-services-modelmesh-runtime-adapter.html?url'
import reportRedHatDataServicesVllmCpu from './generated-reports/quality-report-red-hat-data-services-vllm-cpu.html?url'
import reportRedHatDataServicesModelmesh from './generated-reports/quality-report-red-hat-data-services-modelmesh.html?url'
import reportCaikitCaikitNlp from './generated-reports/quality-report-caikit-caikit-nlp.html?url'
import reportRedHatDataServicesVllmGaudi from './generated-reports/quality-report-red-hat-data-services-vllm-gaudi.html?url'
import reportRedHatDataServicesRestProxy from './generated-reports/quality-report-red-hat-data-services-rest-proxy.html?url'
import reportOpendatahubIoModelmeshRuntimeAdapter from './generated-reports/quality-report-opendatahub-io-modelmesh-runtime-adapter.html?url'
import reportKserveModelmeshRuntimeAdapter from './generated-reports/quality-report-kserve-modelmesh-runtime-adapter.html?url'
import reportOpenvinotoolkitOpenvinoContrib from './generated-reports/quality-report-openvinotoolkit-openvino_contrib.html?url'
import reportKserveModelmesh from './generated-reports/quality-report-kserve-modelmesh.html?url'
import reportOpendatahubIoCaikitNlp from './generated-reports/quality-report-opendatahub-io-caikit-nlp.html?url'
import reportOpendatahubIoRestProxy from './generated-reports/quality-report-opendatahub-io-rest-proxy.html?url'
import reportRedHatDataServicesCaikitNlp from './generated-reports/quality-report-red-hat-data-services-caikit-nlp.html?url'
import reportOpendatahubIoModelmesh from './generated-reports/quality-report-opendatahub-io-modelmesh.html?url'
import reportRedHatDataServicesCaikitTgisServing from './generated-reports/quality-report-red-hat-data-services-caikit-tgis-serving.html?url'
import reportOpendatahubIoOpenvinoContrib from './generated-reports/quality-report-opendatahub-io-openvino_contrib.html?url'
import reportOpendatahubIoVllmGaudi from './generated-reports/quality-report-opendatahub-io-vllm-gaudi.html?url'
import reportTritonInferenceServerClient from './generated-reports/quality-report-triton-inference-server-client.html?url'
import reportRedHatDataServicesOpenvinoContrib from './generated-reports/quality-report-red-hat-data-services-openvino_contrib.html?url'
import reportRedHatDataServicesTextGenerationInference from './generated-reports/quality-report-red-hat-data-services-text-generation-inference.html?url'
import reportTrustyaiExplainabilityVllmOrchestratorGateway from './generated-reports/quality-report-trustyai-explainability-vllm-orchestrator-gateway.html?url'
import reportKserveRestProxy from './generated-reports/quality-report-kserve-rest-proxy.html?url'
import reportOpendatahubIoCaikitTgisServing from './generated-reports/quality-report-opendatahub-io-caikit-tgis-serving.html?url'
import reportOpendatahubIoModelRuntimesAgent from './generated-reports/quality-report-opendatahub-io-model-runtimes-agent.html?url'
import reportRedHatDataServicesVllmOrchestratorGateway from './generated-reports/quality-report-red-hat-data-services-vllm-orchestrator-gateway.html?url'
import reportOpendatahubIoVllmOrchestratorGateway from './generated-reports/quality-report-opendatahub-io-vllm-orchestrator-gateway.html?url'
import reportOpendatahubIoClient from './generated-reports/quality-report-opendatahub-io-client.html?url'
import reportRedHatDataServicesVllm from './generated-reports/quality-report-red-hat-data-services-vllm.html?url'
import reportOpendatahubIoKserveRawMigration from './generated-reports/quality-report-opendatahub-io-kserve-raw-migration.html?url'
import reportRedHatDataServicesMinioModelStorage from './generated-reports/quality-report-red-hat-data-services-minio-model-storage.html?url'
import reportRedHatDataServicesVllmRocm from './generated-reports/quality-report-red-hat-data-services-vllm-rocm.html?url'
import reportRedHatDataServicesModelServingDevops from './generated-reports/quality-report-red-hat-data-services-model-serving-devops.html?url'
import reportRedHatDataServicesVllmSpyre from './generated-reports/quality-report-red-hat-data-services-vllm-spyre.html?url'
import reportOpendatahubIoKserveMigration from './generated-reports/quality-report-opendatahub-io-kserve-migration.html?url'

export const QUALITY_SAMPLE_META = {
  generatedAt: '2026-05-28 22:05:47',
  averageScore: '4.9/10',
  blurb:
    'Model Serving (upstream + midstream + downstream) — all tiers'
}

/** @type {Array<{ id: string, label: string, githubUrl: string, score: string, gaps: string, tier: string, component: string, team: string, reportUrl: string }>} */
export const QUALITY_REPORTS = [
  {
    id: 'kserve-kserve',
    label: 'kserve/kserve',
    githubUrl: 'https://github.com/kserve/kserve',
    score: '8.2/10',
    gaps:
      'No AI agent rules for test automation, No PR-time container vulnerability scanning',
    tier: 'upstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportKserveKserve
  },
  {
    id: 'red-hat-data-services-kserve',
    label: 'red-hat-data-services/kserve',
    githubUrl: 'https://github.com/red-hat-data-services/kserve',
    score: '8.1/10',
    gaps:
      'No container vulnerability scanning in CI, No agent rules for AI-assisted development',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesKserve
  },
  {
    id: 'opendatahub-io-kserve',
    label: 'opendatahub-io/kserve',
    githubUrl: 'https://github.com/opendatahub-io/kserve',
    score: '7.9/10',
    gaps:
      'No container vulnerability scanning (Trivy/Grype/Snyk), No SBOM generation or image signing',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoKserve
  },
  {
    id: 'opendatahub-io-openvino.genai',
    label: 'opendatahub-io/openvino.genai',
    githubUrl: 'https://github.com/opendatahub-io/openvino.genai',
    score: '7.6/10',
    gaps:
      'No code coverage tracking or enforcement, No agent rules or AI-assisted development guidance',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoOpenvinoGenai
  },
  {
    id: 'opendatahub-io-openvino',
    label: 'opendatahub-io/openvino',
    githubUrl: 'https://github.com/opendatahub-io/openvino',
    score: '7.6/10',
    gaps:
      'No coverage enforcement on PRs, No container security scanning (Trivy/Snyk)',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoOpenvino
  },
  {
    id: 'openvinotoolkit-openvino',
    label: 'openvinotoolkit/openvino',
    githubUrl: 'https://github.com/openvinotoolkit/openvino',
    score: '7.6/10',
    gaps:
      'No container vulnerability scanning, No PR-level coverage enforcement',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpenvinotoolkitOpenvino
  },
  {
    id: 'red-hat-data-services-models-as-a-service',
    label: 'red-hat-data-services/models-as-a-service',
    githubUrl: 'https://github.com/red-hat-data-services/models-as-a-service',
    score: '7.4/10',
    gaps:
      'No PR-time Docker image build validation, No coverage enforcement or threshold',
    tier: 'downstream',
    component: 'Model as a Service',
    team: 'Crimson',
    reportUrl: reportRedHatDataServicesModelsAsAService
  },
  {
    id: 'openvinotoolkit-openvino.genai',
    label: 'openvinotoolkit/openvino.genai',
    githubUrl: 'https://github.com/openvinotoolkit/openvino.genai',
    score: '7.2/10',
    gaps:
      'No code coverage tracking or enforcement, No container image testing',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpenvinotoolkitOpenvinoGenai
  },
  {
    id: 'opendatahub-io-models-as-a-service',
    label: 'opendatahub-io/models-as-a-service',
    githubUrl: 'https://github.com/opendatahub-io/models-as-a-service',
    score: '7.0/10',
    gaps:
      'No coverage enforcement or threshold tracking, No container image security scanning',
    tier: 'midstream',
    component: 'Model as a Service',
    team: 'Crimson',
    reportUrl: reportOpendatahubIoModelsAsAService
  },
  {
    id: 'opendatahub-io-openvino_tokenizers',
    label: 'opendatahub-io/openvino_tokenizers',
    githubUrl: 'https://github.com/opendatahub-io/openvino_tokenizers',
    score: '6.8/10',
    gaps:
      'No container image testing or Dockerfile, No code coverage tracking or enforcement',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoOpenvinoTokenizers
  },
  {
    id: 'openvinotoolkit-openvino_tokenizers',
    label: 'openvinotoolkit/openvino_tokenizers',
    githubUrl: 'https://github.com/openvinotoolkit/openvino_tokenizers',
    score: '6.8/10',
    gaps:
      'No code coverage instrumentation or reporting, No container image testing infrastructure',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpenvinotoolkitOpenvinoTokenizers
  },
  {
    id: 'red-hat-data-services-openvino_model_server',
    label: 'red-hat-data-services/openvino_model_server',
    githubUrl: 'https://github.com/red-hat-data-services/openvino_model_server',
    score: '6.8/10',
    gaps:
      'No PR-time unit test execution in GitHub Actions, No codecov/coveralls integration for PR coverage reporting',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesOpenvinoModelServer
  },
  {
    id: 'red-hat-data-services-openvino',
    label: 'red-hat-data-services/openvino',
    githubUrl: 'https://github.com/red-hat-data-services/openvino',
    score: '6.5/10',
    gaps:
      'No downstream/Red Hat-specific CI or testing, No container image builds or Dockerfiles',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesOpenvino
  },
  {
    id: 'opendatahub-io-MLServer',
    label: 'opendatahub-io/MLServer',
    githubUrl: 'https://github.com/opendatahub-io/MLServer',
    score: '6.4/10',
    gaps: 'Zero test coverage tracking, No image runtime validation',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoMlserver
  },
  {
    id: 'openvinotoolkit-model_server',
    label: 'openvinotoolkit/model_server',
    githubUrl: 'https://github.com/openvinotoolkit/model_server',
    score: '6.4/10',
    gaps:
      'No public CI/CD - all Jenkins pipelines are internal-only, No container vulnerability scanning (Trivy/Snyk/Grype)',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpenvinotoolkitModelServer
  },
  {
    id: 'red-hat-data-services-modelmesh-serving',
    label: 'red-hat-data-services/modelmesh-serving',
    githubUrl: 'https://github.com/red-hat-data-services/modelmesh-serving',
    score: '6.4/10',
    gaps:
      'No coverage tracking or enforcement, No container vulnerability scanning in CI',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesModelmeshServing
  },
  {
    id: 'opendatahub-io-modelmesh-serving',
    label: 'opendatahub-io/modelmesh-serving',
    githubUrl: 'https://github.com/opendatahub-io/modelmesh-serving',
    score: '6.2/10',
    gaps:
      'No coverage tracking or enforcement, No container image security scanning',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoModelmeshServing
  },
  {
    id: 'opendatahub-io-odh-model-controller',
    label: 'opendatahub-io/odh-model-controller',
    githubUrl: 'https://github.com/opendatahub-io/odh-model-controller',
    score: '6.2/10',
    gaps:
      'E2E tests are not automated on PRs, No security scanning (Trivy, Snyk, CodeQL, gosec)',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoOdhModelController
  },
  {
    id: 'opendatahub-io-vllm-tgis-adapter',
    label: 'opendatahub-io/vllm-tgis-adapter',
    githubUrl: 'https://github.com/opendatahub-io/vllm-tgis-adapter',
    score: '6.2/10',
    gaps:
      'No container image build or test in this repository, No security scanning (SAST, dependency, container)',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoVllmTgisAdapter
  },
  {
    id: 'red-hat-data-services-odh-model-controller',
    label: 'red-hat-data-services/odh-model-controller',
    githubUrl: 'https://github.com/red-hat-data-services/odh-model-controller',
    score: '6.2/10',
    gaps:
      'E2E tests are manual-only (workflow_dispatch), No coverage tracking or enforcement',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesOdhModelController
  },
  {
    id: 'red-hat-data-services-MLServer',
    label: 'red-hat-data-services/MLServer',
    githubUrl: 'https://github.com/red-hat-data-services/MLServer',
    score: '6.1/10',
    gaps:
      'No code coverage tracking or enforcement, No PR-time Docker image build validation',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesMlserver
  },
  {
    id: 'opendatahub-io-openvino_model_server',
    label: 'opendatahub-io/openvino_model_server',
    githubUrl: 'https://github.com/opendatahub-io/openvino_model_server',
    score: '5.9/10',
    gaps:
      'No PR-time unit test or build validation in GitHub Actions, No container vulnerability scanning (Trivy/Snyk) in CI',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoOpenvinoModelServer
  },
  {
    id: 'SeldonIO-MLServer',
    label: 'SeldonIO/MLServer',
    githubUrl: 'https://github.com/SeldonIO/MLServer',
    score: '5.7/10',
    gaps:
      'Zero test coverage tracking, No PR-time Docker build validation',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportSeldonioMlserver
  },
  {
    id: 'kserve-modelmesh-serving',
    label: 'kserve/modelmesh-serving',
    githubUrl: 'https://github.com/kserve/modelmesh-serving',
    score: '5.6/10',
    gaps:
      'No coverage tracking or enforcement, No container vulnerability scanning',
    tier: 'upstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportKserveModelmeshServing
  },
  {
    id: 'opendatahub-io-caikit-nlp-client',
    label: 'opendatahub-io/caikit-nlp-client',
    githubUrl: 'https://github.com/opendatahub-io/caikit-nlp-client',
    score: '5.6/10',
    gaps:
      'Repository appears abandoned — zero commits in 2025, No security scanning in CI (CodeQL, Trivy, Dependabot)',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoCaikitNlpClient
  },
  {
    id: 'red-hat-data-services-modelmesh-runtime-adapter',
    label: 'red-hat-data-services/modelmesh-runtime-adapter',
    githubUrl: 'https://github.com/red-hat-data-services/modelmesh-runtime-adapter',
    score: '5.6/10',
    gaps:
      'No test coverage tracking or enforcement, No integration or E2E tests',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesModelmeshRuntimeAdapter
  },
  {
    id: 'red-hat-data-services-vllm-cpu',
    label: 'red-hat-data-services/vllm-cpu',
    githubUrl: 'https://github.com/red-hat-data-services/vllm-cpu',
    score: '5.6/10',
    gaps:
      'No automated test execution in CI for this fork, No PR-time container image build validation',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesVllmCpu
  },
  {
    id: 'red-hat-data-services-modelmesh',
    label: 'red-hat-data-services/modelmesh',
    githubUrl: 'https://github.com/red-hat-data-services/modelmesh',
    score: '5.4/10',
    gaps:
      'No test coverage tracking or enforcement, No PR-time Konflux build validation',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesModelmesh
  },
  {
    id: 'caikit-caikit-nlp',
    label: 'caikit/caikit-nlp',
    githubUrl: 'https://github.com/caikit/caikit-nlp',
    score: '5.2/10',
    gaps:
      'No integration or E2E test suite, No coverage enforcement or PR reporting',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportCaikitCaikitNlp
  },
  {
    id: 'red-hat-data-services-vllm-gaudi',
    label: 'red-hat-data-services/vllm-gaudi',
    githubUrl: 'https://github.com/red-hat-data-services/vllm-gaudi',
    score: '5.2/10',
    gaps:
      'No coverage tracking or enforcement, No automated PR-time test execution',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesVllmGaudi
  },
  {
    id: 'red-hat-data-services-rest-proxy',
    label: 'red-hat-data-services/rest-proxy',
    githubUrl: 'https://github.com/red-hat-data-services/rest-proxy',
    score: '5.1/10',
    gaps:
      'No integration or E2E tests, No coverage tracking or enforcement',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesRestProxy
  },
  {
    id: 'opendatahub-io-modelmesh-runtime-adapter',
    label: 'opendatahub-io/modelmesh-runtime-adapter',
    githubUrl: 'https://github.com/opendatahub-io/modelmesh-runtime-adapter',
    score: '4.9/10',
    gaps:
      'No test coverage tracking or enforcement, No container image runtime validation',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoModelmeshRuntimeAdapter
  },
  {
    id: 'kserve-modelmesh-runtime-adapter',
    label: 'kserve/modelmesh-runtime-adapter',
    githubUrl: 'https://github.com/kserve/modelmesh-runtime-adapter',
    score: '4.8/10',
    gaps:
      'Repository archived — no active development, Zero coverage tracking or enforcement',
    tier: 'upstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportKserveModelmeshRuntimeAdapter
  },
  {
    id: 'openvinotoolkit-openvino_contrib',
    label: 'openvinotoolkit/openvino_contrib',
    githubUrl: 'https://github.com/openvinotoolkit/openvino_contrib',
    score: '4.8/10',
    gaps:
      'Zero test coverage tracking or enforcement, OpenVINO Code extension has 0 test files for 54 source files',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpenvinotoolkitOpenvinoContrib
  },
  {
    id: 'kserve-modelmesh',
    label: 'kserve/modelmesh',
    githubUrl: 'https://github.com/kserve/modelmesh',
    score: '4.6/10',
    gaps:
      'No code coverage tracking, No container image security scanning',
    tier: 'upstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportKserveModelmesh
  },
  {
    id: 'opendatahub-io-caikit-nlp',
    label: 'opendatahub-io/caikit-nlp',
    githubUrl: 'https://github.com/opendatahub-io/caikit-nlp',
    score: '4.6/10',
    gaps:
      'No integration or E2E tests, No coverage enforcement or codecov integration',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoCaikitNlp
  },
  {
    id: 'opendatahub-io-rest-proxy',
    label: 'opendatahub-io/rest-proxy',
    githubUrl: 'https://github.com/opendatahub-io/rest-proxy',
    score: '4.6/10',
    gaps:
      'No integration or E2E tests, No container vulnerability scanning',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoRestProxy
  },
  {
    id: 'red-hat-data-services-caikit-nlp',
    label: 'red-hat-data-services/caikit-nlp',
    githubUrl: 'https://github.com/red-hat-data-services/caikit-nlp',
    score: '4.6/10',
    gaps:
      'No codecov or coverage enforcement in CI, No integration or E2E test suites',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesCaikitNlp
  },
  {
    id: 'opendatahub-io-modelmesh',
    label: 'opendatahub-io/modelmesh',
    githubUrl: 'https://github.com/opendatahub-io/modelmesh',
    score: '4.5/10',
    gaps:
      'PRs to main branch have NO CI checks, No code coverage tracking',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoModelmesh
  },
  {
    id: 'red-hat-data-services-caikit-tgis-serving',
    label: 'red-hat-data-services/caikit-tgis-serving',
    githubUrl: 'https://github.com/red-hat-data-services/caikit-tgis-serving',
    score: '4.5/10',
    gaps: 'No unit tests at all, No coverage tracking or enforcement',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesCaikitTgisServing
  },
  {
    id: 'opendatahub-io-openvino_contrib',
    label: 'opendatahub-io/openvino_contrib',
    githubUrl: 'https://github.com/opendatahub-io/openvino_contrib',
    score: '4.2/10',
    gaps:
      'No code coverage tracking or enforcement, No container image security scanning',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoOpenvinoContrib
  },
  {
    id: 'opendatahub-io-vllm-gaudi',
    label: 'opendatahub-io/vllm-gaudi',
    githubUrl: 'https://github.com/opendatahub-io/vllm-gaudi',
    score: '4.2/10',
    gaps:
      'No test execution in GitHub Actions CI, No code coverage tracking',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoVllmGaudi
  },
  {
    id: 'triton-inference-server-client',
    label: 'triton-inference-server/client',
    githubUrl: 'https://github.com/triton-inference-server/client',
    score: '4.2/10',
    gaps:
      'No tests execute in CI/CD, No coverage tracking or enforcement',
    tier: 'upstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportTritonInferenceServerClient
  },
  {
    id: 'red-hat-data-services-openvino_contrib',
    label: 'red-hat-data-services/openvino_contrib',
    githubUrl: 'https://github.com/red-hat-data-services/openvino_contrib',
    score: '4.1/10',
    gaps:
      'No code coverage tracking or enforcement, No container image security scanning',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesOpenvinoContrib
  },
  {
    id: 'red-hat-data-services-text-generation-inference',
    label: 'red-hat-data-services/text-generation-inference',
    githubUrl: 'https://github.com/red-hat-data-services/text-generation-inference',
    score: '3.8/10',
    gaps:
      'Zero Rust test coverage, No code coverage tracking or enforcement',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesTextGenerationInference
  },
  {
    id: 'trustyai-explainability-vllm-orchestrator-gateway',
    label: 'trustyai-explainability/vllm-orchestrator-gateway',
    githubUrl: 'https://github.com/trustyai-explainability/vllm-orchestrator-gateway',
    score: '3.5/10',
    gaps:
      'Minimal unit test coverage — only config validation tested, No integration or E2E tests',
    tier: 'upstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportTrustyaiExplainabilityVllmOrchestratorGateway
  },
  {
    id: 'kserve-rest-proxy',
    label: 'kserve/rest-proxy',
    githubUrl: 'https://github.com/kserve/rest-proxy',
    score: '3.4/10',
    gaps:
      'No integration or E2E tests, No coverage tracking or enforcement',
    tier: 'upstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportKserveRestProxy
  },
  {
    id: 'opendatahub-io-caikit-tgis-serving',
    label: 'opendatahub-io/caikit-tgis-serving',
    githubUrl: 'https://github.com/opendatahub-io/caikit-tgis-serving',
    score: '3.4/10',
    gaps: 'Zero unit tests, No code coverage tracking',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoCaikitTgisServing
  },
  {
    id: 'opendatahub-io-model-runtimes-agent',
    label: 'opendatahub-io/model-runtimes-agent',
    githubUrl: 'https://github.com/opendatahub-io/model-runtimes-agent',
    score: '3.2/10',
    gaps:
      'No CI/CD pipeline of any kind, No coverage tracking or enforcement',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoModelRuntimesAgent
  },
  {
    id: 'red-hat-data-services-vllm-orchestrator-gateway',
    label: 'red-hat-data-services/vllm-orchestrator-gateway',
    githubUrl: 'https://github.com/red-hat-data-services/vllm-orchestrator-gateway',
    score: '2.9/10',
    gaps:
      'Minimal unit test coverage — core request handling untested, Zero integration or E2E tests',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesVllmOrchestratorGateway
  },
  {
    id: 'opendatahub-io-vllm-orchestrator-gateway',
    label: 'opendatahub-io/vllm-orchestrator-gateway',
    githubUrl: 'https://github.com/opendatahub-io/vllm-orchestrator-gateway',
    score: '2.2/10',
    gaps:
      'No tests for core request handling logic (main.rs), No integration or E2E tests',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoVllmOrchestratorGateway
  },
  {
    id: 'opendatahub-io-client',
    label: 'opendatahub-io/client',
    githubUrl: 'https://github.com/opendatahub-io/client',
    score: '1.9/10',
    gaps: 'No test execution in CI, Zero coverage tracking',
    tier: 'midstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportOpendatahubIoClient
  },
  {
    id: 'red-hat-data-services-vllm',
    label: 'red-hat-data-services/vllm',
    githubUrl: 'https://github.com/red-hat-data-services/vllm',
    score: '1.4/10',
    gaps:
      'No container image runtime validation, skip-checks=true in Tekton pipeline',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesVllm
  },
  {
    id: 'opendatahub-io-kserve-raw-migration',
    label: 'opendatahub-io/kserve-raw-migration',
    githubUrl: 'https://github.com/opendatahub-io/kserve-raw-migration',
    score: '1.2/10',
    gaps: 'Zero test coverage - no tests of any kind, No CI/CD pipeline',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoKserveRawMigration
  },
  {
    id: 'red-hat-data-services-minio-model-storage',
    label: 'red-hat-data-services/minio-model-storage',
    githubUrl: 'https://github.com/red-hat-data-services/minio-model-storage',
    score: '1.2/10',
    gaps: 'No CI/CD pipeline of any kind, Zero test coverage',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesMinioModelStorage
  },
  {
    id: 'red-hat-data-services-vllm-rocm',
    label: 'red-hat-data-services/vllm-rocm',
    githubUrl: 'https://github.com/red-hat-data-services/vllm-rocm',
    score: '1.0/10',
    gaps:
      'No runtime validation of built container image, No automated tests of any kind',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesVllmRocm
  },
  {
    id: 'red-hat-data-services-model-serving-devops',
    label: 'red-hat-data-services/model-serving-devops',
    githubUrl: 'https://github.com/red-hat-data-services/model-serving-devops',
    score: '0.8/10',
    gaps:
      'Zero test coverage for automation scripts, No PR-triggered CI workflow',
    tier: 'downstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportRedHatDataServicesModelServingDevops
  },
  {
    id: 'red-hat-data-services-vllm-spyre',
    label: 'red-hat-data-services/vllm-spyre',
    githubUrl: 'https://github.com/red-hat-data-services/vllm-spyre',
    score: '0.8/10',
    gaps: 'No CI/CD pipeline at all, No image build validation on PR',
    tier: 'downstream',
    component: 'Model Runtimes',
    team: 'General',
    reportUrl: reportRedHatDataServicesVllmSpyre
  },
  {
    id: 'opendatahub-io-kserve-migration',
    label: 'opendatahub-io/kserve-migration',
    githubUrl: 'https://github.com/opendatahub-io/kserve-migration',
    score: '0.5/10',
    gaps:
      'Repository is an empty placeholder — no source code, No CI/CD workflows',
    tier: 'midstream',
    component: 'Model Serving',
    team: 'General',
    reportUrl: reportOpendatahubIoKserveMigration
  },
]

