apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../../base
- cronjob-sync-refresh.yaml

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  - AUTH_EMAIL_DOMAIN=cluster.local
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: af9e7a2d6120a80da6df31300abd13894d1768a5
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: 77f575cf74b9cc0409f6275202e675d5b7907c49
