apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../../base
- cronjob-sync-refresh.yaml

patches:
- path: route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: 5bec5334f0165fbfbfb936ad3b136790ab40c320
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: 723fa29d03e18c9750d3fed14eed6f842c4043eb
