/**
 * Centralized view-to-owner mapping, auto-populated from git history.
 *
 * DO NOT EDIT MANUALLY — regenerated by scripts/update-view-owners.js
 * Run: npm run update:view-owners
 *
 * Each key is "moduleSlug/viewId" and the value is the display name of the
 * person who first introduced that view's component file.
 *
 * This mapping is also consumed by the org-pulse chatbot integration.
 * Admin overrides from data/view-owner-overrides.json are merged in during generation.
 */
export const viewOwners = {
  // ai-catalyst
  'ai-catalyst/board':                             'Nati Fridman',
  'ai-catalyst/candidate-detail':                  'Nati Fridman',
  'ai-catalyst/catalog':                           'Nati Fridman',
  'ai-catalyst/report':                            'Nati Fridman',
  'ai-catalyst/showcase-detail':                   'Nati Fridman',

  // ai-impact
  'ai-impact/ai-factory-guide':                    'Alex Corvin',
  'ai-impact/autofix':                             'Alex Corvin',
  'ai-impact/build-release':                       'Deepak Chourasia',
  'ai-impact/documentation':                       'tarilabs',
  'ai-impact/feature-review':                      'Alex Corvin',
  'ai-impact/implementation':                      'Alex Corvin',
  'ai-impact/rfe-review':                          'Alex Corvin',
  'ai-impact/security':                            'Alex Corvin',
  'ai-impact/test-plan-review':                    'Kamesh Akella',

  // customer-insights
  'customer-insights/dashboard':                   'ankristo-rh',
  'customer-insights/import':                      'ankristo-rh',
  'customer-insights/kanban':                      'ankristo-rh',
  'customer-insights/rfe-creator':                 'ankristo-rh',
  'customer-insights/roadmap':                     'ankristo-rh',

  // okr-hub
  'okr-hub/deep-dive':                             'Saiesh Prabhu',
  'okr-hub/reports':                               'Saiesh Prabhu',
  'okr-hub/timeline':                              'Saiesh Prabhu',

  // pm-pipeline
  'pm-pipeline/learn':                             'Jen Albertson',
  'pm-pipeline/my-pipeline':                       'Jen Albertson',
  'pm-pipeline/planning-prep':                     'Jen Albertson',

  // product-builds
  'product-builds/artifact-detail':                'Pavol Pitonak',
  'product-builds/base-images':                    'Pavol Pitonak',
  'product-builds/builder-images':                 'Pavol Pitonak',
  'product-builds/drop-detail':                    'Pavol Pitonak',
  'product-builds/overview':                       'Giulia Naponiello',
  'product-builds/package-analysis':               'Einat Pacifici',
  'product-builds/rhaiis':                         'Pavol Pitonak',
  'product-builds/rhel-ai':                        'Pavol Pitonak',
  'product-builds/series-detail':                  'Giulia Naponiello',
  'product-builds/wheel-collections':              'Pavol Pitonak',

  // releases
  'releases/audit':                                'Alex Corvin',
  'releases/deliver':                              'Alex Corvin',
  'releases/execute':                              'Alex Corvin',
  'releases/feature-detail':                       'shuels2',
  'releases/plan':                                 'Alex Corvin',
  'releases/registry':                             'Alex Corvin',
  'releases/reports':                              'Alex Corvin',
  'releases/schedule':                             'Paul McCarthy',

  // system-health
  'system-health/component-maturity':              'Dana Gutride',
  'system-health/disconnected-repo-detail':        'Ajay Jaganathan',
  'system-health/quality-analysis':                'Dana Gutride',

  // team-tracker
  'team-tracker/home':                             'Dipanshu Gupta',
  'team-tracker/jira-taxonomy':                    'Alex Corvin',
  'team-tracker/manage':                           'Alex Corvin',
  'team-tracker/manager-dashboard':                'Alex Corvin',
  'team-tracker/org-dashboard':                    'Alex Corvin',
  'team-tracker/org-explorer':                     'Dipanshu Gupta',
  'team-tracker/people':                           'Dipanshu Gupta',
  'team-tracker/person-detail':                    'Dipanshu Gupta',
  'team-tracker/reports':                          'Alex Corvin',
  'team-tracker/team-detail':                      'Alex Corvin',
  'team-tracker/unassigned':                       'Alex Corvin',

  // upstream-pulse
  'upstream-pulse/dashboard':                      'Dipanshu Gupta',
  'upstream-pulse/insights':                       'Dipanshu Gupta',
  'upstream-pulse/org-detail':                     'Dipanshu Gupta',
  'upstream-pulse/portfolio':                      'Dipanshu Gupta',
  'upstream-pulse/project-detail':                 'Dipanshu Gupta',
  'upstream-pulse/strategy':                       'Dipanshu Gupta',

  // ── Sub-tab owners (module/view/tab) ──
  // These override the view-level owner when a specific tab is active.

  // releases > execute
  'releases/execute/feature-list':                 'Alex Corvin',
  'releases/execute/feature-status':               'Saiesh Prabhu',

  // releases > plan
  'releases/plan/bu-feedback':                     'Saiesh Prabhu',
  'releases/plan/feature-readiness':               'Erle Marion',
  'releases/plan/outcomes':                        'Erle Marion',

  // releases > registry
  'releases/registry/hygiene':                     'Alex Corvin',

  // system-health > component-maturity
  'system-health/component-maturity/disconnected': 'Ajay Jaganathan',

  // team-tracker > manage
  'team-tracker/manage/data-quality':              'Alex Corvin',
  'team-tracker/manage/field-options':             'Alex Corvin',
  'team-tracker/manage/fields':                    'Alex Corvin',
  'team-tracker/manage/teams':                     'Alex Corvin',

  // ── Report owners (module/view/reportId) ──
  // These override the view-level owner when a specific report is selected.

  // releases > reports
  'releases/reports/cve-sustaining':               'Saiesh Prabhu',
  'releases/reports/feature-pressure':             'Dimitri Saridakis',
  'releases/reports/program-hygiene':              'Alex Corvin',
  'releases/reports/release-readiness':            'Arthy Loganathan',
  'releases/reports/tv-fv-delta':                  'Dimitri Saridakis',

  // team-tracker > reports
  'team-tracker/reports/allocation':               'Alex Corvin',
  'team-tracker/reports/team-comparison':          'Alex Corvin',
  'team-tracker/reports/trends':                   'Alex Corvin',
}

/**
 * Look up the owner of a view, with optional sub-view granularity.
 * Supports both ?tab= and ?report= query params as sub-view identifiers.
 * Resolution order: sub-view-specific override > sub-view-specific default >
 *                   view-level override > view-level default.
 * @param {string} moduleSlug
 * @param {string} viewId
 * @param {Object} [overrides] - Admin overrides from view-owner-overrides.json
 * @param {string} [subView] - Active sub-view id (tab or report from query params)
 * @returns {string | null} Display name of the owner
 */
export function getViewOwner(moduleSlug, viewId, overrides = {}, subView = null) {
  const viewKey = `${moduleSlug}/${viewId}`
  if (subView) {
    const subKey = `${viewKey}/${subView}`
    if (overrides[subKey]) return overrides[subKey]
    if (viewOwners[subKey]) return viewOwners[subKey]
  }
  return overrides[viewKey] || viewOwners[viewKey] || null
}
