/**
 * Centralized view-to-owner mapping, auto-populated from git history.
 *
 * DO NOT EDIT MANUALLY — regenerated by scripts/update-view-owners.js
 * Run: npm run update:view-owners
 *
 * Each key is "moduleSlug/viewId" and the value is the display name of the
 * person who first introduced that view's component file.
 *
 * This mapping is also consumed by the org-pulse chatbot integration.
 * Admin overrides from data/view-owner-overrides.json are merged in during generation.
 */
export const viewOwners = {
  // ai-catalyst
  'ai-catalyst/board':                             'github-actions[bot]',
  'ai-catalyst/candidate-detail':                  'github-actions[bot]',
  'ai-catalyst/catalog':                           'github-actions[bot]',
  'ai-catalyst/report':                            'github-actions[bot]',
  'ai-catalyst/showcase-detail':                   'github-actions[bot]',

  // ai-impact
  'ai-impact/ai-factory-guide':                    'github-actions[bot]',
  'ai-impact/autofix':                             'github-actions[bot]',
  'ai-impact/build-release':                       'github-actions[bot]',
  'ai-impact/documentation':                       'github-actions[bot]',
  'ai-impact/feature-decomposer':                  'github-actions[bot]',
  'ai-impact/feature-review':                      'github-actions[bot]',
  'ai-impact/implementation':                      'github-actions[bot]',
  'ai-impact/rfe-review':                          'github-actions[bot]',
  'ai-impact/security':                            'github-actions[bot]',
  'ai-impact/test-plan-review':                    'github-actions[bot]',

  // customer-insights
  'customer-insights/dashboard':                   'github-actions[bot]',
  'customer-insights/import':                      'github-actions[bot]',
  'customer-insights/kanban':                      'github-actions[bot]',
  'customer-insights/rfe-creator':                 'github-actions[bot]',
  'customer-insights/roadmap':                     'github-actions[bot]',

  // okr-hub
  'okr-hub/deep-dive':                             'github-actions[bot]',
  'okr-hub/reports':                               'github-actions[bot]',
  'okr-hub/timeline':                              'github-actions[bot]',

  // pm-pipeline
  'pm-pipeline/learn':                             'github-actions[bot]',
  'pm-pipeline/my-pipeline':                       'github-actions[bot]',
  'pm-pipeline/planning-prep':                     'github-actions[bot]',

  // product-builds
  'product-builds/artifact-detail':                'github-actions[bot]',
  'product-builds/base-images':                    'github-actions[bot]',
  'product-builds/builder-images':                 'github-actions[bot]',
  'product-builds/drop-detail':                    'github-actions[bot]',
  'product-builds/overview':                       'github-actions[bot]',
  'product-builds/package-analysis':               'github-actions[bot]',
  'product-builds/rhaiis':                         'github-actions[bot]',
  'product-builds/rhel-ai':                        'github-actions[bot]',
  'product-builds/search':                         'github-actions[bot]',
  'product-builds/series-detail':                  'github-actions[bot]',
  'product-builds/wheel-collections':              'github-actions[bot]',

  // releases
  'releases/audit':                                'github-actions[bot]',
  'releases/deliver':                              'github-actions[bot]',
  'releases/execute':                              'github-actions[bot]',
  'releases/feature-detail':                       'github-actions[bot]',
  'releases/plan':                                 'github-actions[bot]',
  'releases/registry':                             'github-actions[bot]',
  'releases/reports':                              'github-actions[bot]',
  'releases/schedule':                             'github-actions[bot]',

  // system-health
  'system-health/component-maturity':              'github-actions[bot]',
  'system-health/disconnected-repo-detail':        'github-actions[bot]',
  'system-health/e2e-run-detail':                  'github-actions[bot]',
  'system-health/odh-e2e-health':                  'github-actions[bot]',
  'system-health/quality-analysis':                'github-actions[bot]',

  // team-tracker
  'team-tracker/jira-taxonomy':                    'github-actions[bot]',

  // upstream-pulse
  'upstream-pulse/dashboard':                      'github-actions[bot]',
  'upstream-pulse/insights':                       'github-actions[bot]',
  'upstream-pulse/org-detail':                     'github-actions[bot]',
  'upstream-pulse/portfolio':                      'github-actions[bot]',
  'upstream-pulse/project-detail':                 'github-actions[bot]',
  'upstream-pulse/strategy':                       'github-actions[bot]',

  // ── Sub-tab owners (module/view/tab) ──
  // These override the view-level owner when a specific tab is active.

  // releases > execute
  'releases/execute/feature-list':                 'github-actions[bot]',
  'releases/execute/feature-status':               'github-actions[bot]',

  // releases > plan
  'releases/plan/bu-feedback':                     'github-actions[bot]',
  'releases/plan/feature-readiness':               'github-actions[bot]',
  'releases/plan/outcomes':                        'github-actions[bot]',

  // releases > registry
  'releases/registry/hygiene':                     'github-actions[bot]',

  // system-health > component-maturity
  'system-health/component-maturity/disconnected': 'github-actions[bot]',

  // ── Report owners (module/view/reportId) ──
  // These override the view-level owner when a specific report is selected.

  // releases > reports
  'releases/reports/ai-adoption':                  'github-actions[bot]',
  'releases/reports/capacity-commitment':          'github-actions[bot]',
  'releases/reports/component-architectures':      'github-actions[bot]',
  'releases/reports/cve-sustaining':               'github-actions[bot]',
  'releases/reports/feature-pressure':             'github-actions[bot]',
  'releases/reports/program-hygiene':              'github-actions[bot]',
  'releases/reports/release-readiness':            'github-actions[bot]',
  'releases/reports/tv-fv-delta':                  'github-actions[bot]',
}

/**
 * Look up the owner of a view, with optional sub-view granularity.
 * Supports both ?tab= and ?report= query params as sub-view identifiers.
 * Resolution order: sub-view-specific override > sub-view-specific default >
 *                   view-level override > view-level default.
 * @param {string} moduleSlug
 * @param {string} viewId
 * @param {Object} [overrides] - Admin overrides from view-owner-overrides.json
 * @param {string} [subView] - Active sub-view id (tab or report from query params)
 * @returns {string | null} Display name of the owner
 */
export function getViewOwner(moduleSlug, viewId, overrides = {}, subView = null) {
  const viewKey = `${moduleSlug}/${viewId}`
  if (subView) {
    const subKey = `${viewKey}/${subView}`
    if (overrides[subKey]) return overrides[subKey]
    if (viewOwners[subKey]) return viewOwners[subKey]
  }
  return overrides[viewKey] || viewOwners[viewKey] || null
}
