#!/usr/bin/env node

/**
 * Validates the OpenAPI spec generated by swagger-jsdoc.
 *
 * 1. Checks the spec is valid OpenAPI 3.x via @apidevtools/swagger-parser
 * 2. Compares the number of documented paths against expected counts
 * 3. Scans route source files for router.verb() calls and flags any that
 *    lack a preceding @openapi annotation
 */

const SwaggerParser = require('@apidevtools/swagger-parser');
const path = require('path');
const fs = require('fs');

function collectJsFiles(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...collectJsFiles(full));
    else if (entry.name.endsWith('.js')) results.push(full);
  }
  return results;
}

/**
 * Scans JS source files for Express route registrations that are missing
 * an @openapi JSDoc annotation. Returns an array of { file, line, route }
 * objects for each undocumented route.
 */
function findUndocumentedRoutes() {
  const rootDir = path.resolve(__dirname, '..');
  const files = [path.join(rootDir, 'server/dev-server.js')];

  // Scan all module server directories
  const modulesDir = path.join(rootDir, 'modules');
  if (fs.existsSync(modulesDir)) {
    for (const mod of fs.readdirSync(modulesDir, { withFileTypes: true })) {
      if (!mod.isDirectory()) continue;
      const serverDir = path.join(modulesDir, mod.name, 'server');
      if (fs.existsSync(serverDir)) files.push(...collectJsFiles(serverDir));
    }
  }

  const routeRegex = /(?:router|app)\.(get|post|put|patch|delete)\(\s*['"`]([^'"`]+)['"`]/;
  const missing = [];

  for (const filePath of files) {
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const match = lines[i].match(routeRegex);
      if (!match) continue;

      const method = match[1].toUpperCase();
      const route = match[2];

      // Look backwards for @openapi in the preceding comment block
      // Some annotations with many parameters can span 50+ lines
      let hasAnnotation = false;
      for (let j = i - 1; j >= Math.max(0, i - 60); j--) {
        const prev = lines[j].trim();
        if (prev === '' || prev === '*/') continue;
        // Skip single-line comments between annotation and route
        if (prev.startsWith('//')) continue;
        if (prev.startsWith('*') || prev.startsWith('/**')) {
          if (prev.includes('@openapi') || prev.includes('@swagger')) {
            hasAnnotation = true;
            break;
          }
          continue;
        }
        // Hit a non-comment line — stop looking
        break;
      }

      if (!hasAnnotation) {
        const relPath = path.relative(rootDir, filePath);
        missing.push({ file: relPath, line: i + 1, route: `${method} ${route}` });
      }
    }
  }

  return missing;
}

async function main() {
  // Generate spec
  const { createOpenApiSpec } = require('../server/openapi-config');
  const spec = createOpenApiSpec();

  // 1. Validate spec structure
  console.log('Validating OpenAPI spec...');
  try {
    await SwaggerParser.validate(JSON.parse(JSON.stringify(spec)));
    console.log('  OpenAPI spec is valid.');
  } catch (err) {
    console.error('  OpenAPI spec validation FAILED:', err.message);
    process.exit(1);
  }

  // 2. Coverage snapshot
  const expectedPath = path.join(__dirname, 'openapi-route-count.json');
  const expected = JSON.parse(fs.readFileSync(expectedPath, 'utf8'));

  const specPaths = Object.keys(spec.paths || {});
  const totalPaths = specPaths.length;
  const totalExpected = Object.values(expected).reduce((sum, n) => sum + n, 0);

  // Count operations (GET, POST, etc.) not just paths
  let totalOperations = 0;
  for (const pathItem of Object.values(spec.paths || {})) {
    for (const method of ['get', 'post', 'put', 'delete', 'patch', 'options']) {
      if (pathItem[method]) totalOperations++;
    }
  }

  console.log(`  Documented paths: ${totalPaths}`);
  console.log(`  Documented operations: ${totalOperations}`);
  console.log(`  Expected operations: ${totalExpected}`);

  if (totalOperations < totalExpected) {
    console.error(`  FAIL: Expected at least ${totalExpected} operations but found ${totalOperations}.`);
    console.error('  Some routes may be missing @openapi annotations.');
    process.exit(1);
  }

  console.log('  Coverage check passed.');

  // 3. Scan for undocumented routes
  console.log('\nScanning for undocumented routes...');
  const missing = findUndocumentedRoutes();

  if (missing.length > 0) {
    console.warn(`  WARNING: Found ${missing.length} route(s) without @openapi annotations:\n`);
    for (const m of missing) {
      console.warn(`    ${m.file}:${m.line}  ${m.route}`);
    }
    console.warn('\n  Add @openapi JSDoc annotations to these routes.');
  } else {
    console.log('  All routes have @openapi annotations.');
  }
  console.log('\nOpenAPI validation complete.');
}

main().catch(function(err) {
  console.error('Unexpected error:', err);
  process.exit(1);
});
