#!/usr/bin/env node

/**
 * Validates the OpenAPI spec generated by swagger-jsdoc.
 *
 * 1. Checks the spec is valid OpenAPI 3.x via @apidevtools/swagger-parser
 * 2. Compares the number of documented paths against expected counts
 */

const SwaggerParser = require('@apidevtools/swagger-parser');
const path = require('path');
const fs = require('fs');

async function main() {
  // Generate spec
  const { createOpenApiSpec } = require('../server/openapi-config');
  const spec = createOpenApiSpec();

  // 1. Validate spec structure
  console.log('Validating OpenAPI spec...');
  try {
    await SwaggerParser.validate(JSON.parse(JSON.stringify(spec)));
    console.log('  OpenAPI spec is valid.');
  } catch (err) {
    console.error('  OpenAPI spec validation FAILED:', err.message);
    process.exit(1);
  }

  // 2. Coverage snapshot
  const expectedPath = path.join(__dirname, 'openapi-route-count.json');
  const expected = JSON.parse(fs.readFileSync(expectedPath, 'utf8'));

  const specPaths = Object.keys(spec.paths || {});
  const totalPaths = specPaths.length;
  const totalExpected = Object.values(expected).reduce((sum, n) => sum + n, 0);

  // Count operations (GET, POST, etc.) not just paths
  let totalOperations = 0;
  for (const pathItem of Object.values(spec.paths || {})) {
    for (const method of ['get', 'post', 'put', 'delete', 'patch', 'options']) {
      if (pathItem[method]) totalOperations++;
    }
  }

  console.log(`  Documented paths: ${totalPaths}`);
  console.log(`  Documented operations: ${totalOperations}`);
  console.log(`  Expected operations: ${totalExpected}`);

  if (totalOperations < totalExpected) {
    console.error(`  FAIL: Expected at least ${totalExpected} operations but found ${totalOperations}.`);
    console.error('  Some routes may be missing @openapi annotations.');
    process.exit(1);
  }

  console.log('  Coverage check passed.');
  console.log('\nOpenAPI validation complete.');
}

main().catch(function(err) {
  console.error('Unexpected error:', err);
  process.exit(1);
});
